"""Add image field to poems table

Revision ID: 19f4f5b8c638
Revises: 158fb10f9603
Create Date: 2024-12-18 14:29:07.585817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19f4f5b8c638'
down_revision: Union[str, None] = '158fb10f9603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poems', sa.Column('image', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poems', 'image')
    # ### end Alembic commands ###
